language: node_js
node_js:
    - "node"
env:
    global:
        - TEST_FIREFOX_BIN="${TRAVIS_HOME}/firefox-latest-unsigned/firefox/firefox"
        - TEST_HEADLESS=1
        - COVERALLS_PARALLEL=true
dist: xenial
install:
    - lsb_release -a
    - npm install
    - npm ls; true
jobs:
    include:
        - stage: lint
          env: TEST_SUITE=lint
          script:
              - npm run lint

        - stage: unit
          env: TEST_SUITE=unit
          script:
              - npm run test:unit:coveralls

        - stage: integration
          env: TEST_SUITE=integration
          addons:
              firefox: latest-unsigned
          script:
              - '"$TEST_FIREFOX_BIN" --version'
              - npm run test:integration:coveralls

notifications:
    webhooks: https://coveralls.io/webhook
