language: node_js
node_js:
    - "node"
env:
    global:
        - TEST_FIREFOX_BIN="${TRAVIS_HOME}/firefox-latest-unsigned/firefox/firefox"
        - TEST_HEADLESS=1
dist: xenial
install:
    - lsb_release -a
    - npm install
    - npm ls; true
jobs:
    include:
        - stage: lint
          env: TEST_SUITE=lint
          script:
              - npm run lint

        - stage: test
          env: TEST_SUITE=unit,integration
          addons:
              firefox: latest-unsigned
          script:
              - '"$TEST_FIREFOX_BIN" --version'
              - npm run test:unit:coveralls
