'use strict';
const WS_CLOSE_NORMAL = 1000;
const WS_CLOSE_ABNORMAL_CLOSURE = 1006;
const WS_CLOSE_POLICY_VIOLATION = 1008;
// (4000-4999 is for private use)
const WS_CLOSE_TIMEOUT = 4000;

module.exports = {
    WS_CLOSE_NORMAL,
    WS_CLOSE_ABNORMAL_CLOSURE,
    WS_CLOSE_POLICY_VIOLATION,
    WS_CLOSE_TIMEOUT,
};
